language: node_js
node_js:
  - "lts/*"
script:
  - sh deploy.sh
if: branch = dev
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master